### ISSUE TITLE
ERROR: An error has occurred. Check your logs or contact the app author for clarification.

### ISSUE THREAD

**Issue by jagerzhang** [microsoft/TagAnomaly#11]
Run with docker container: 

```
docker run -p 80:3838 -d --name=test omri374/taganomaly
```
It's report this error:

```
ERROR: An error has occurred. Check your logs or contact the app author for clarification.
```

![image](https://user-images.githubusercontent.com/9711651/55225945-c48ccf80-524e-11e9-872b-6ee88c0bf3a2.png)

**Comment by omri374** [comment]
Hi, thanks for reaching out. I'll look into this

**Comment by omri374** [comment]
Fixed. please review. PR #13. Sorry for the delay
