### ISSUE TITLE
The UI gets no response after running for a while

### ISSUE THREAD

**Issue by qqdaiyu55** [microsoft/TagAnomaly#18]
**User-System**: MacOS 10.15
**Deployment**: deployed on Azure Container with the docker image
**Chrome**: 80.0.3987.149 (Official Build) (64-bit)
**Problem**: The UI get stuck after out of focus for a while.
**Detail**: I uploaded a 11M size file and tried to analyze the time series. After running for a while (switch to other workspaces or browser tabs), I found the UI got no response, and the bug can be reproduced.
When I clicked the tab buttons, there's no response, and the error message in console is 
```
shinyapp.js:288 Uncaught TypeError: Cannot read property 'readyState' of null
    at ShinyApp.$sendMsg (shinyapp.js:288)
    at ShinyApp.sendInput (shinyapp.js:140)
    at InputBatchSender.$sendNow (input_rate.js:220)
```

<img width="1188" alt="Screen Shot 2020-03-24 at 6 20 28 PM" src="https://user-images.githubusercontent.com/9846706/77415050-dfac0400-6dfc-11ea-9d5c-7c774e914c2e.png">

**Comment by omri374** [comment]
Hi,
Sounds like a bug in Shiny (maybe a duplicate of this: https://stackoverflow.com/questions/54470702/r-shiny-apps-greys-out-and-hangs)

Have you tried spinning up a larger compute for Azure Container Instances?

**Comment by qqdaiyu55** [comment]
@omri374 Thanks for advice. I tried 4v CPU and 8G memory, and it didn't work. Seem that I have to deploy it on my local machine as the temporary solution.

**Comment by qqdaiyu55** [comment]
Consider it's an issue of shiny server, I'll close this issue. Solved it with the solution in https://github.com/virtualstaticvoid/heroku-buildpack-r/issues/97

**Comment by JeanBertinR** [comment]
I have exactly the same problem ( Shiny screen greyed out) after about 1 sec when launching the app from remote clients. Everything works fine on Rstudio Desktop. 
The solution proposed here [/virtualstaticvoid/heroku-buildpack-r/issues/97] didn't solve the problem because my app crashes instantly when loading the app... 
Any suggestion ?

**Comment by Painthamil** [comment]
I am facing the same issue as well, my app crashes instantly when loading the app. Did anyone was able to solve this?
Thanks

**Comment by omri374** [comment]
@Painthamil where/how are you deploying the app?

**Comment by Painthamil** [comment]
@omri374 In shinyapps.io

**Comment by omri374** [comment]
@Painthamil if it's the free tier, I believe it's by design.
